# audit-sink-deployments-services.yaml
apiVersion: audit.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: my-deployments-services-sink
spec:
  webhook:
    clientConfig:
      # Substitua por sua URL do webhook
      url: http://192.168.1.160:3001/api/webhook
    throttle:
      qps: 10
      burst: 10
  policy:
    # Capturar eventos em diferentes estágios
    stages:
    - "Request"
    - "ResponseComplete"
    rules:
      # Regra para auditoria de Deployments
      - level: Request
        resources:
          - group: "apps"
            resources:
              - "deployments"
        verbs:
          - "create"
          - "delete"
      # Regra para auditoria de Services
      - level: Request
        resources:
          - group: ""  # "" significa que o recurso está no core API
            resources:
              - "services"
        verbs:
          - "create"
          - "delete"