
# WhatsApp Backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsap
  template:
    metadata:
      labels:
        app: whatsap
    spec:
      containers:
        - name: whatsap
          image: alexsandrojsilva0/whatsap:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: "production"
            - name: TOKEN
              value: "132"
            - name: USERID
              value: "123"
            - name: API_URL
              value: "http://api:3001"
            - name: DEV
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: whatsap
spec:
  type: LoadBalancer
  selector:
    app: whatsap
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

