---
# Namespace (opcional)
apiVersion: v1
kind: Namespace
metadata:
  name: default

---
# PersistentVolumeClaim para armazenar modelos (evita baixar toda vez)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Ajuste conforme o modelo (8B ~5-10GB, 70B ~40GB+)

---
# Deployment do Ollama
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: default
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
              name: api
          env:
            # Força o Ollama a escutar em todas as interfaces (necessário no k8s)
            - name: OLLAMA_HOST
              value: "0.0.0.0"
            # (Opcional) Especifica o modelo a ser pré-carregado
            - name: OLLAMA_MODELS
              value: "/root/.ollama/models"
          volumeMounts:
            - name: models
              mountPath: /root/.ollama
          # (Opcional) Recursos — ajuste conforme sua GPU/CPU
          resources:
            limits:
              cpu: "4"
              memory: "16Gi"
              # Se tiver GPU NVIDIA, descomente abaixo:
              # nvidia.com/gpu: 1
            requests:
              cpu: "2"
              memory: "8Gi"
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: ollama-pvc
      # (Opcional) Tolerations para nodes com GPU
      # tolerations:
      #   - key: "nvidia.com/gpu"
      #     operator: "Exists"
      #     effect: "NoSchedule"

---
# Service para expor internamente (ou externamente com LoadBalancer/NodePort)
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: default
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP  # Use "LoadBalancer" ou "NodePort" se quiser acesso externo

---
# (Opcional) Job para pré-carregar um modelo
apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-pull-model
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: pull-model
          image: ollama/ollama:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              ollama pull llama3.1:8b
          volumeMounts:
            - name: models
              mountPath: /root/.ollama
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: ollama-pvc
      restartPolicy: OnFailure
  backoffLimit: 4