# Use uma imagem oficial do Node.js (recomendado)
FROM node:18

# Instalar dependências do sistema necessárias para o whatsapp-web.js / puppeteer
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgbm1 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxrandr2 \
    libatk1.0-0 \
    libpangocairo-1.0-0 \
    libgtk-3-0 \
    libasound2 \
    libatk-bridge2.0-0 \
    libnss3 \
    fonts-noto \
    libxss1 \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Diretório de trabalho
WORKDIR /usr/src/whatsapp

# Copiar código do repositório diretamente (ou usar git clone se preferir)
RUN git clone https://github.com/AlexsandroJ/WhatsapWebServer.git  . && \
    npm install

# Expor a porta da aplicação
EXPOSE 5001

# Comando para iniciar a aplicação
CMD ["npm", "start"]