# Use a imagem oficial do Jenkins com JDK 11 como base
FROM jenkins/jenkins:lts-jdk17

# Defina o usuário root para instalar pacotes
USER root

# Instale o JDK 17
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java

# Instale dependências necessárias e Docker
RUN apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io

# Baixe e instale o Docker Compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

# Torne o Jenkins o usuário padrão novamente
USER jenkins