# Usar a imagem base oficial do Nginx
FROM nginx:latest

# Instalar dependências básicas (Git, Curl, etc.)
RUN apt-get update && apt-get install -y git curl

# Instalar o Node.js (versão LTS recomendada)
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs

# Definir o diretório de trabalho temporário para clonar o repositório
WORKDIR /tmp/repo

# Clonar o repositório Git contendo o projeto Next.js
RUN git clone https://github.com/AlexsandroJ/frontESS.git . || echo "Erro ao clonar"

# Instalar as dependências do projeto Next.js
RUN npm install

# Executar o build do projeto Next.js
RUN npm run build

# Exportar o projeto Next.js para produção (gera arquivos estáticos no diretório 'out')
RUN npm run export

# Definir o diretório de trabalho para o Nginx
WORKDIR /usr/share/nginx/html

# Remover o index.html padrão do Nginx
RUN rm -f index.html

# Copiar os arquivos gerados pelo Next.js para o diretório do Nginx
COPY --from=0 /tmp/repo/out/* .

# Configurar o Nginx para servir os arquivos estáticos corretamente
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Comando para rodar o Nginx
CMD ["nginx", "-g", "daemon off;"]
