# Use uma imagem oficial do Node.js (recomendado)
FROM node:18

# Instalar dependências do sistema necessárias para o whatsapp-web.js / puppeteer
RUN apt-get update && apt-get install -y \
    git \
    wget \
    libgbm-dev \
    libx11-xcb-dev \
    libxcomposite-dev \
    libasound2-dev \
    fonts-noto \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Diretório de trabalho
WORKDIR /usr/src/app

# Copiar código do repositório diretamente (ou usar git clone se preferir)
RUN git clone https://github.com/AlexsandroJ/WhatsapWebServer.git  . && \
    npm install

# Expor a porta da aplicação
EXPOSE 5001

# Comando para iniciar a aplicação
CMD ["npm", "start"]