FROM jenkins/jenkins:lts-jdk17
# if we want to install via apt
USER root
# Instale o Docker
RUN apt-get update && \
    apt-get install -y \
    ca-certificates \
    curl
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
RUN apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io
# Baixe e instale o Docker Compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose
# Torne o Jenkins o usuário padrão novamente
USER jenkins