
volumes:
  mongo-data:
  portainer_data:

networks:
  net-geral:

services:
 
  whatsap:
    container_name: whatsap
    build:
      context: .
      dockerfile: Dockerfile-whatsap
    ports:
      - "5001:5001"
    networks:
      - net-geral
    environment:
      - NODE_ENV=production
      - API_URL=http://api:3001
      - DEV=false
    restart: always
    depends_on:
        - api

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
