volumes:
  mongo-data:
  app-data:
  nginx-html-data:
  nginx-logs-data:
  nginx-config-data:

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    working_dir: /usr/src/app
    volumes:
      - app-data:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    # Adiciona o comando para clonar o repositório e instalar dependências

  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
        - nginx-html-data:/var/www/html
        - nginx-logs-data:/var/log/nginx
        - nginx-config-data:/etc/nginx/conf.d
    ports:
        - "80:80"
        - "443:443"

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

