version: '3.8'

services:
  app:
    image: node:latest
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    networks: 
      - minha-rede
    depends_on:
      - mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    # Adiciona o comando para clonar o repositório e instalar dependências
    entrypoint: /bin/bash -c "git clone https://github.com/AlexsandroJ/whatsapp-api.git . && npm install && npm start "
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  nginx:
    image: nginx
    container_name: nginx
    ports:
        - "80:80"
    networks: 
        - minha-rede
    depends_on:
        - "app"
volumes:
  mongo-data:
networks:
  minha-rede:
