
volumes:
  mongo-data:
  portainer_data:

networks:
  net-geral:

services:
 
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - net-geral
    restart: always

  api:
    container_name: api
    image: alexsandrojsilva0/api:82c4c16
    #build:
    #  context: .
    #  dockerfile: Dockerfile-api
    ports:
      - "3001:3001"
    networks:
      - net-geral
    environment:
      - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9JWT
      - NODE_ENV=production
      - PORT=3001
      - API_URL=http://api:3001
      - MIN_SIZE_PASSWORD=6
      - COLLECTION_NAME_CLIENT_ZAP=collection_zap
      - COLLECTION_NAME_CLIENT_PEDIDOS=collection_pedidos
      - COLLECTION_NAME_CLIENT_PAGAMENTOS=collection_pagamentos

      - GOOGLE_CLIENT_ID=566156554431-2qmrdv6eagv44rq6n07c1mvupak41v6t.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - REDIRECT_URI=http://localhost:3000/testApi

      - DB_USER=root
      - DB_PASS=example
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=tests
      - DEV=false
    restart: always
    depends_on:
        - mongo

  next:
    container_name: next
    image: alexsandrojsilva0/next:9a52ea5
    #build:
    #  context: .
    #  dockerfile: Dockerfile-next
    ports:
      - 3000:3000
    networks:
      - net-geral
    environment:
      - NEXT_PUBLIC_APIBASEURL=http://api:3001
    restart: always
    pull_policy: always
    depends_on:
        - api
        - whatsap

  #portainer:
  #  image: portainer/portainer-ce
  #  container_name: portainer
  #  restart: always
  #  ports:
  #    - "9000:9000"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - portainer_data:/data
