services:
  app:
    image: alpine
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - alpine-data:/usr/src/app
    ports:
      - "3000:3000"
    networks: 
      - minha
    #depends_on:
      #- mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    # Adiciona o comando para clonar o repositório e instalar dependências
    #entrypoint: "apk update ; apk add git nodejs npm ; git clone https://github.com/AlexsandroJ/docker.git .  ; npm install ; npm start "
    entrypoint: "apk add nodejs"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  nginx:
    image: nginx
    container_name: nginx
    ports:
        - "80:80"
    networks: 
        - minha-rede
    depends_on:
        - "app"
volumes:
  mongo-data:
  alpine-data:
networks:
  minha-rede:
  minha:
