FROM ubuntu

# Atualizar repositórios e instalar Node.js, npm e Git
RUN apt update \
    && apt install -y nodejs npm git nano

# Definir o diretório de trabalho
WORKDIR /usr/src/app

RUN git clone https://github.com/AlexsandroJ/apiProjects.git . \
    && npm install
    
# Expor a porta que a aplicação usará
EXPOSE 3001

# Comando para iniciar a aplicação
CMD ["npm","start"]

