# Stage 1: Build the application
FROM node:22 AS builder

# Define working directory
WORKDIR /app

# Instalar Git (necessário para clonar repositório)
RUN apt-get update && apt-get install -y git

# Clona o repositório GitHub
RUN git clone https://github.com/AlexsandroJ/dashboardProjects.git  .

# Instala dependências - forma mais segura
RUN npm ci

# Faz o build da aplicação Next.js
RUN npm run build

# Stage 2: Servir a aplicação
FROM node:22 AS runner

# Diretório de trabalho
WORKDIR /app

# Cria usuário não-root para segurança
RUN groupadd --system appgroup && useradd --system -g appgroup appuser
USER appuser
COPY --chown=appuser:appgroup --from=builder /app/.next ./.next
COPY --chown=appuser:appgroup --from=builder /app/node_modules ./node_modules
COPY --chown=appuser:appgroup --from=builder /app/package.json ./package.json

# Expor porta
EXPOSE 3000

# Iniciar a aplicação
CMD ["npm", "start"]