# k3s-api-access.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-access
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: api-access-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: api-access
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-access-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: api-access
  namespace: default