name: Build and Push Docker Hub NEXT Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'start'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version from git tag or commit hash
        id: vars
        run: |
          version=$(git describe --tags --always 2>/dev/null)
          if [[ $? -ne 0 ]]; then
            version=$(git rev-parse --short HEAD)
          fi
          echo "version=$version" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Image NEXT
        run: |
          docker build \
            -f Dockerfile-next \
            --label "org.opencontainers.image.revision=$(git rev-parse HEAD)" \
            --label "org.opencontainers.image.version=${{ env.version }}" \
            -t $DOCKER_USER/next:${{ env.version }} .

          docker tag $DOCKER_USER/next:${{ env.version }} $DOCKER_USER/next:latest

          docker push $DOCKER_USER/next:${{ env.version }}
          docker push $DOCKER_USER/next:latest