name: Build and Push Docker HUB API Image

on:
  workflow_dispatch:  # Evento manual de acionamento da pipeline
    inputs:
      environment:
        description: 'Environment to deploy to'  # Descrição do input
        required: true
        default: 'start'  # Valor padrão

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version from git tag
        id: vars
        run: |
          echo "version=$(git describe --tags)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Image API
        run: |
          docker build -f Dockerfile-api -t $DOCKER_USER/api:${{ env.version }} .
          docker push $DOCKER_USER/api:${{ env.version }}