name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version from commit hash
        id: vars
        run: |
          echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Image API
        run: |
          docker build -f Dockerfile-api -t $DOCKER_USER/api:${{ env.version }} .
          docker push $DOCKER_USER/api:${{ env.version }}

      - name: Build and Push Image WHATSAP
        run: |
          docker build -f Dockerfile-whatsap -t $DOCKER_USER/whatsap:${{ env.version }} .
          docker push $DOCKER_USER/whatsap:${{ env.version }}

      - name: Build and Push Image NEXT
        run: |
          docker build -f Dockerfile-next -t $DOCKER_USER/next:${{ env.version }} .
          docker push $DOCKER_USER/next:${{ env.version }}